import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { rawAtlasDocumentSchema } from "./atlas-schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = join(__dirname, "..", "data", "ATLAS.yaml");
const DEST_PATH = join(__dirname, "..", "src", "atlas-data.ts");

const GROUP_KEYS = ["tactics", "techniques", "mitigations", "case-studies"] as const;

export function compileAtlasData(): void {
  const raw = readFileSync(SOURCE_PATH, "utf-8");
  const doc = parse(raw) as Record<string, unknown>;

  const data: Record<string, unknown> = {};
  for (const key of GROUP_KEYS) {
    data[key] = doc[key] ?? {};
  }

  const result = rawAtlasDocumentSchema.safeParse(data);
  if (!result.success) {
    throw new Error(
      `${SOURCE_PATH} does not match the shape expected by src/types.ts:\n${result.error.toString()}`,
    );
  }

  const contents = `// Generated by \`npm run compile-data\` from data/ATLAS.yaml. Do not edit by hand.
import type { RawAtlasDocument } from "./types.js";

export const rawAtlasData: RawAtlasDocument = ${JSON.stringify(data, null, 2)};
`;

  writeFileSync(DEST_PATH, contents, "utf-8");
  console.log(`Wrote ${DEST_PATH}`);
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  compileAtlasData();
}
