import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import type { AtlasObject } from "../src/types.js";
import { buildAtlasUrl } from "../src/urls.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = join(__dirname, "..", "data", "ATLAS.yaml");
const DEST_PATH = join(__dirname, "..", "src", "atlas-data.ts");
const OBJECTS_DIR = join(__dirname, "..", "src", "data");

const GROUP_KEYS = ["tactics", "techniques", "mitigations", "case-studies"] as const;

function writePerObjectModules(data: Record<string, unknown>): void {
  if (existsSync(OBJECTS_DIR)) {
    rmSync(OBJECTS_DIR, { recursive: true });
  }
  mkdirSync(OBJECTS_DIR, { recursive: true });

  const ids: string[] = [];
  for (const groupKey of GROUP_KEYS) {
    const group = data[groupKey] as Record<string, Omit<AtlasObject, "url">>;
    for (const [id, object] of Object.entries(group)) {
      if (id === "manifest") {
        throw new Error(`ATLAS ID "manifest" collides with the generated manifest module`);
      }
      const withUrl: AtlasObject = { ...object, url: buildAtlasUrl(object["object-type"], id) } as AtlasObject;
      const contents = `// Generated by \`npm run compile-data\` from data/ATLAS.yaml. Do not edit by hand.
import type { AtlasObject } from "../types.js";

const object: AtlasObject = ${JSON.stringify(withUrl, null, 2)};

export default object;
`;
      writeFileSync(join(OBJECTS_DIR, `${id}.ts`), contents, "utf-8");
      ids.push(id);
    }
  }
  ids.sort();

  const manifestContents = `// Generated by \`npm run compile-data\` from data/ATLAS.yaml. Do not edit by hand.
export const atlasObjectIds: ReadonlySet<string> = new Set(${JSON.stringify(ids, null, 2)});
`;
  writeFileSync(join(OBJECTS_DIR, "manifest.ts"), manifestContents, "utf-8");
  console.log(`Wrote ${ids.length} per-object modules to ${OBJECTS_DIR}`);
}

export function compileAtlasData(): void {
  const raw = readFileSync(SOURCE_PATH, "utf-8");
  const doc = parse(raw) as Record<string, unknown>;

  const data: Record<string, unknown> = {};
  for (const key of GROUP_KEYS) {
    data[key] = doc[key] ?? {};
  }

  const contents = `// Generated by \`npm run compile-data\` from data/ATLAS.yaml. Do not edit by hand.
import type { RawAtlasDocument } from "./types.js";

export const rawAtlasData: RawAtlasDocument = ${JSON.stringify(data, null, 2)};
`;

  writeFileSync(DEST_PATH, contents, "utf-8");
  console.log(`Wrote ${DEST_PATH}`);

  writePerObjectModules(data);
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  compileAtlasData();
}
